name: Run ETL Time Travel

on:
  workflow_dispatch:
    inputs:
      class:
        type: choice
        description: Class
        options:
          - com.taxis.etl.travel_time.TravelTime
          - com.taxis.etl.payments_distance.PaymentsDistance
        default: com.taxis.etl.travel_time.TravelTime
      hilos:
        description: "Numero de hilos de procesador"
        default: "1"
      pi:
        description: "Spark Pi Program"
        default: "100"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.1.2'
        hadoop-version: '2.7'
    - run: spark-submit --version
    - name: Run build with Gradle Wrapper
      run: ./gradlew assemble
    - run: mkdir ./build/libs/resources
    - name: Download parquet file 2020
      run: curl -L https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2020-01.parquet -o yellow_tripdata_2020-01.parquet
      working-directory: ./build/libs/resources
    - name: Download parquet file 2021
      run: curl -L https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet -o yellow_tripdata_2021-01.parquet
      working-directory: ./build/libs/resources
    - name: Download parquet file 2022
      run: curl -L https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-01.parquet -o yellow_tripdata_2022-01.parquet
      working-directory: ./build/libs/resources
    - name: Run spark submit for ${{ github.event.inputs.class }}
      run: spark-submit --class ${{ github.event.inputs.class }} --master local[${{ github.event.inputs.hilos }}] taxisEtl.jar ${{ github.event.inputs.pi }}
      working-directory: ./build/libs
    - name: Archive ETL results
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: build/libs/results
